// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc295.TestDrivetrain;


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap 
{
	
	// CAN IDs ARE UNIQUE PER DEVICE TYPE
    public static final   short  CAN_ESC_DRIVE_LEFT_FRONT             = 0;
    public static final   short  CAN_ESC_DRIVE_LEFT_BACK              = 1;
    public static final   short  CAN_ESC_DRIVE_RIGHT_FRONT            = 2;
    public static final   short  CAN_ESC_DRIVE_RIGHT_BACK             = 3;	

    public static final   short  CAN_PCM_MODULE                       = 0;	
    public static final   short  CAN_PCM_PORT_SHIFTER                 = 1;	
    
    
    // PWM PINS (0 - 20)
    public static final   short  PWM_ESC_DRIVE_LEFT_FRONT             = 0;
    public static final   short  PWM_ESC_DRIVE_LEFT_BACK              = 1;
    public static final   short  PWM_ESC_DRIVE_RIGHT_FRONT            = 2;
    public static final   short  PWM_ESC_DRIVE_RIGHT_BACK             = 3;
    
    // DIGITAL IO PINS
    public static final   short  DIO_ENC_DRIVE_RIGHT_CHAN1            = 0;
    public static final   short  DIO_ENC_DRIVE_RIGHT_CHAN2            = 1;
    public static final   short  DIO_ENC_DRIVE_LEFT_CHAN1             = 2;
    public static final   short  DIO_ENC_DRIVE_LEFT_CHAN2             = 3;
    
    
    public static void init()
    {
    }
}
